<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Error</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="css/custom.css" rel="stylesheet" type="text/css"/>
</head>

<body>

<div class="container">
    <div class="alert alert-warning" id ="error" role="alert">
    ${errors_message}
    </div>
</div>
</body>
</html>